### ISSUE TITLE
LAME memory may leak in case of error during initialization

### ISSUE THREAD

**Issue by DoumanAsh** [henkelmax/lame4j#1]
Plain C code and FFI bindings would not have destructor implemented, so you cannot just do `drop(lame)` here
https://github.com/henkelmax/lame4j/blob/master/rust/src/lame/encoder.rs#L30

To be sure you need to perform `lame_close`  on this pointer like there https://github.com/henkelmax/lame4j/blob/master/rust/src/lame/encoder.rs#L154

**Comment by henkelmax** [comment]
Thank you for reporting this!
